### ISSUE TITLE
[Enhancement]  Rule 34/Iphone support?

### ISSUE THREAD

**Issue by TheTzar** [PawCorp/walltaker-desktop-client#33]
Has anyone voiced potentially adding support for rule34 as well?
I completely understand the appeal of blacklisting and using well moderated sites instead of just random images, and I would love to use this app for other stuff that isn't inherently furry.

Basically implement another version of Walltaker or allow users to pick either, or both websites

I love the concept and how smoothly this app works, I feel like other communities would embrace this too.

I am also an iPhone user and would love to have a version for my phone, but currently there is no API for it.
Is that because Apple is difficult to develop for?

Thanks!

**Comment by oddpawsx** [comment]
Hi there, I'll address the two separate issues reported here.

> Has anyone voiced potentially adding support for rule34 as well?

I haven't specifically heard any requests for this but that being said, this would require an upstream change to the [web service that runs Walltaker](https://github.com/PawCorp/walltaker) first, before any changes to the client apps are considered. It is written specifically with e621 in mind for furries, so we would need changes there before client apps are equipped to handle other sources. I'd suggest opening an issue there for discussion. 

> iPhone version

[As far as I can tell,](https://developer.apple.com/forums/thread/110679?answerId=339444022#339444022) there is no way to update iOS wallpapers programmatically.
